functionsDirectory = "/home/administrator/arc-autopay/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/home/administrator/arc-autopay/public"
publishOrigin = "config"
functions = "/home/administrator/arc-autopay/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/pay"
to = "/.netlify/functions/concord"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]